import { Outfit } from "next/font/google";
import "./globals.css";

const outer = Outfit({ subsets: ["latin"], weight: ["400","500","600","700"] });

export const metadata = {
  title: "Planner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outer.className}>{children}</body>
    </html>
  );
}

